server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/musicplayer?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 20253
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效
# 配置打印sql语句
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.uniproject.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
